### ISSUE TITLE
Ver outros simuladores do ambiente do Mario

### ISSUE THREAD

**Issue by EdwardSJ151** [EdwardSJ151/mario-gpt#2]
Devido a quantidade maior de inimigos, provavelmente não podemos usar o simulador do MarioGPT. Portanto, precisamos implementar outro. Pesquise na literatura (o artigo https://ieeexplore.ieee.org/document/6003769 é um bom começo) outros simuladores que podemos implementar.

Bascicamente o input deve ser a fase gerada, e com esses dados (no caso do mariogpt, caracteres, mas podemos processar se necessário) ele deve simular um ambiente do Mario

Veja se o simulador desse repositorio é o suficiente (creio que seja):
https://github.com/amidos2006/Mario-AI-Framework

Também tem o simulador desse paper aqui (Acho que é o mesmo do fangame Infinite Mario Bros):
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6003769
Um repositorio que tem um archive do Infinite Mario Bros:
https://github.com/cflewis/Infinite-Mario-Bros?tab=readme-ov-file
(Não achei o código fonte original, porque parece que ela foi vendida para a Microsoft quando eles compraram a Minecraft. O criador do Infinite Mario Bros é o Notch, e ele usou a mesma tecnologia para o PCG no Minecraft, aí meio que o Infinite Mario Bros foi considerado parte do Minecraft)
Existe uma versão do gerador compativel com o Mario AI Framework:
https://github.com/amidos2006/Mario-AI-Framework/tree/master/src/levelGenerators/notch

O ambiente precisa obrigatoriamente ter suporte para os seguintes itens (o repositorio que mandei acima tem se não me engano):
- Ground
- Bricks
- Hard Blocks
- Question Blocks
- PowerUps in Blocks/Bricks (mushroom, 1up)
- Goomba
- Green Koopa / Winged Green Koopa (?) (Não lembro se ele esta no Mario 1, precisa conferir)
- Red Koopa / Winged Red Koopa (?) (Esse eu tenho quase certeza que está, mas é bom conferir novamente)
- Bullet Bill Blaster
- Spiny
- Pipes

Seria legal também ter:
- Mushroom Platforms/Semisolid Platforms (possuem as mesmas propriedades e só possuem diferença estetica, qualquer um dos dois serve)
- Fire Flower

Outros que não são necessários mas seria legal:
- Hammer Bros

Podemos adicionar a bandeirola de chegada da fase também. Se quiser testar o ambiente, use essa fase aqui do nosso repositorio:
https://github.com/EdwardSJ151/MM2_LevelViewer4AI/blob/main/utils/ASCII_levels.py

Se tiver erros por causa do formato, descubra exatamente qual objeto está dando o erro

**Comment by mendesLet** [comment]
Ambiente Infinite Mario com Wall Jump

- [ ] [Video](https://www.youtube.com/watch?v=DlkMs4ZHHr8)
